{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "###Â Web Scraping Telegram Bot\n",
    "\n",
    "This project was created to demonstrate the use of the BeautifulSoup library\n",
    "and its integration with ever popular Telegram Bot API. \n",
    "\n",
    "In this particular example I will be making a Telegram Bot, which will take \n",
    "text input, that will be used to search a word in the directory on the website \n",
    "and it's dictionary definition scraped from the resulting page. This definition \n",
    "would be then sent as a response to the input in the telegrams dialogue window. \n",
    "\n",
    "In case the word is not listed in the dictionary, the resulting message response\n",
    "in the dialogue window will indicate error."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### FINAL CODE:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Listening ...\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "This event loop is already running",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-11c7fe78c13f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     84\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     85\u001b[0m         \u001b[0;31m# Keep the program running\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 86\u001b[0;31m \u001b[0mloop\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun_forever\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/miniconda3/lib/python3.8/asyncio/base_events.py\u001b[0m in \u001b[0;36mrun_forever\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    558\u001b[0m         \u001b[0;34m\"\"\"Run until stop() is called.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    559\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_closed\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 560\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_running\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    561\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_set_coroutine_origin_tracking\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_debug\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    562\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_thread_id\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mthreading\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_ident\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/asyncio/base_events.py\u001b[0m in \u001b[0;36m_check_running\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    550\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_check_running\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    551\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_running\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 552\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'This event loop is already running'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    553\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mevents\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_running_loop\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    554\u001b[0m             raise RuntimeError(\n",
      "\u001b[0;31mRuntimeError\u001b[0m: This event loop is already running"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    }
   ],
   "source": [
    "# Asyncio is a library to write concurrent code using the async/await syntax.\n",
    "import asyncio\n",
    "\n",
    "# Telepot helps you build applications for Telegram Bot API. \n",
    "import telepot\n",
    "import telepot.aio\n",
    "from telepot.aio.loop import MessageLoop\n",
    "\n",
    "#âPretty-printâ structures in a form which can be used as input to the interpreter.\n",
    "from pprint import pprint\n",
    "\n",
    "#Beautiful Soup is a Python library for pulling data out of HTML and XML files.\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "# Requests is a HTTP library for the Python programming language. \n",
    "import requests\n",
    "\n",
    "# Insert images into Jupyter Notebook\n",
    "from IPython.display import Image\n",
    "\n",
    "\n",
    "\n",
    "# async creates a coroutine function\n",
    "async def handle(msg):\n",
    "    \n",
    "    # making chat_id be accesible outside of the code\n",
    "    global chat_id\n",
    "    \n",
    "    # set variables / https://www.programcreek.com/python/example/105815/telepot.glance\n",
    "    content_type, chat_type, chat_id = telepot.glance(msg)\n",
    "    \n",
    "    #print variables\n",
    "    print(content_type, chat_type, chat_id)\n",
    "    \n",
    "    pprint(msg)\n",
    "    \n",
    "    username = msg['chat']['first_name']\n",
    "    \n",
    "    # Check that the content type is text and it is not \"/start\"\n",
    "    if content_type == 'text':\n",
    "        if msg['text'] != '/start':\n",
    "            text = msg['text']\n",
    "            \n",
    "            # remove all white space charactersâspaces, tabs, new lines\n",
    "            text = text.strip()\n",
    "            \n",
    "            # coroutine await/async - function is paused\n",
    "            await getMeaning(text.lower())\n",
    "            \n",
    "\n",
    "\n",
    "async def getMeaning(text):\n",
    "    \n",
    "    # URL formation\n",
    "    url = 'https://www.urbandictionary.com/define.php?term=' + text\n",
    "    \n",
    "    # gather page response via requests\n",
    "    page = requests.get(url)\n",
    "    \n",
    "    # creation of BaeutifulSoup object \n",
    "    soup = BeautifulSoup(page.text, 'html.parser')\n",
    "    \n",
    "    # pprint(soup) (Figure 1)\n",
    "\n",
    "    try:\n",
    "        try:\n",
    "            \n",
    "            # get definition - we are searching div category (Figure 2)\n",
    "            definition = soup.find('div', {\"class\" : 'meaning'}).text\n",
    "            \n",
    "            await bot.sendMessage(chat_id, definition)\n",
    "\n",
    "        except:\n",
    "            await bot.sendMessage(chat_id, 'Meaning not found!')\n",
    "    except:\n",
    "        await bot.sendMessage(chat_id, 'Something went wrong...')\n",
    "\n",
    "\t# Program startup\n",
    "TOKEN = '1983335411:AAEEtYwPUzBxm1wykQ-BHsM3vnSoNHkh_84'\n",
    "bot = telepot.aio.Bot(TOKEN)\n",
    "loop = asyncio.get_event_loop()\n",
    "loop.create_task(MessageLoop(bot, handle).run_forever())\n",
    "print('Listening ...')\n",
    "\n",
    "\t# Keep the program running\n",
    "loop.run_forever()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Figure 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "No such file or directory: 'img/picture.png'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1292\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1293\u001b[0;31m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: a bytes-like object is required, not 'str'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, obj, include, exclude)\u001b[0m\n\u001b[1;32m    968\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    969\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmethod\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 970\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minclude\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0minclude\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexclude\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mexclude\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    971\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    972\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_repr_mimebundle_\u001b[0;34m(self, include, exclude)\u001b[0m\n\u001b[1;32m   1281\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0membed\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1282\u001b[0m             \u001b[0mmimetype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_mimetype\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1283\u001b[0;31m             \u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmetadata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_data_and_metadata\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0malways_both\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1284\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmetadata\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1285\u001b[0m                 \u001b[0mmetadata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0mmimetype\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mmetadata\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1293\u001b[0m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1295\u001b[0;31m             raise FileNotFoundError(\n\u001b[0m\u001b[1;32m   1296\u001b[0m                 \"No such file or directory: '%s'\" % (self.data))\n\u001b[1;32m   1297\u001b[0m         \u001b[0mmd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: No such file or directory: 'img/picture.png'"
     ]
    },
    {
     "ename": "FileNotFoundError",
     "evalue": "No such file or directory: 'img/picture.png'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1292\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1293\u001b[0;31m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: a bytes-like object is required, not 'str'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, obj)\u001b[0m\n\u001b[1;32m    343\u001b[0m             \u001b[0mmethod\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget_real_method\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprint_method\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    344\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmethod\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 345\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    346\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    347\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_repr_png_\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1311\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_repr_png_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1312\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0membed\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_FMT_PNG\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1313\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_data_and_metadata\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1314\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1315\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_repr_jpeg_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1293\u001b[0m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1295\u001b[0;31m             raise FileNotFoundError(\n\u001b[0m\u001b[1;32m   1296\u001b[0m                 \"No such file or directory: '%s'\" % (self.data))\n\u001b[1;32m   1297\u001b[0m         \u001b[0mmd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: No such file or directory: 'img/picture.png'"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<IPython.core.display.Image object>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    }
   ],
   "source": [
    "Image(\"img/pprint.png\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Figure 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "No such file or directory: 'img/screenshot1.png'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1292\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1293\u001b[0;31m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: a bytes-like object is required, not 'str'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, obj, include, exclude)\u001b[0m\n\u001b[1;32m    968\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    969\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmethod\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 970\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minclude\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0minclude\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexclude\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mexclude\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    971\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    972\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_repr_mimebundle_\u001b[0;34m(self, include, exclude)\u001b[0m\n\u001b[1;32m   1281\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0membed\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1282\u001b[0m             \u001b[0mmimetype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_mimetype\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1283\u001b[0;31m             \u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmetadata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_data_and_metadata\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0malways_both\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1284\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmetadata\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1285\u001b[0m                 \u001b[0mmetadata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0mmimetype\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mmetadata\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1293\u001b[0m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1295\u001b[0;31m             raise FileNotFoundError(\n\u001b[0m\u001b[1;32m   1296\u001b[0m                 \"No such file or directory: '%s'\" % (self.data))\n\u001b[1;32m   1297\u001b[0m         \u001b[0mmd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: No such file or directory: 'img/screenshot1.png'"
     ]
    },
    {
     "ename": "FileNotFoundError",
     "evalue": "No such file or directory: 'img/screenshot1.png'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1292\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1293\u001b[0;31m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: a bytes-like object is required, not 'str'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/formatters.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, obj)\u001b[0m\n\u001b[1;32m    343\u001b[0m             \u001b[0mmethod\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget_real_method\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprint_method\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    344\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mmethod\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 345\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mmethod\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    346\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    347\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_repr_png_\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1311\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_repr_png_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1312\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0membed\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_FMT_PNG\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1313\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_data_and_metadata\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1314\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1315\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_repr_jpeg_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.8/site-packages/IPython/core/display.py\u001b[0m in \u001b[0;36m_data_and_metadata\u001b[0;34m(self, always_both)\u001b[0m\n\u001b[1;32m   1293\u001b[0m             \u001b[0mb64_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mb2a_base64\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'ascii'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1294\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1295\u001b[0;31m             raise FileNotFoundError(\n\u001b[0m\u001b[1;32m   1296\u001b[0m                 \"No such file or directory: '%s'\" % (self.data))\n\u001b[1;32m   1297\u001b[0m         \u001b[0mmd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: No such file or directory: 'img/screenshot1.png'"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<IPython.core.display.Image object>"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/loop.py\", line 29, in run_forever\n",
      "    result = await self._bot.getUpdates(offset=offset,\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 587, in getUpdates\n",
      "    return await self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/__init__.py\", line 78, in _api_request\n",
      "    return await api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 146, in request\n",
      "    return await _parse(r)\n",
      "  File \"/Users/andrey/miniconda3/lib/python3.8/site-packages/telepot/aio/api.py\", line 132, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    }
   ],
   "source": [
    "Image(\"img/screenshot1.png\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
